version: "3"

services:
  management-interest-api:
    image: management-interest-api
    build:
      context: ./Management.Interest
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - softplayer-network
    depends_on:
      - "redisinterest"

  redisinterest:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - softplayer-network

networks: 
    softplayer-network:
        driver: bridge
