version: "3.5"

services:
  redisinterest:
    container_name: redisinterest
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - softplayer-network

  management-interest-api:
    container_name: managementinterestapi
    image: management-interest-api
    build:
      context: ./Management.Interest
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - softplayer-network
    depends_on:
      - "redisinterest"

  accounting-interest-api:
    container_name: accountinginterestapi
    image: accounting-interest-api
    build:
      context: ./Accounting.Interest
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - softplayer-network
    depends_on:
      - "management-interest-api"
      - "redisinterest"

networks: 
    softplayer-network:
        driver: bridge
        name: softplayernetwork